name: SHRP C18Pro Arch
on:
  workflow_dispatch:
    inputs:
      FLAVOR:
        description: 'FLAVOR'
        required: true
        default: 'eng'

env:
  BOT_API: ${{ secrets.BOT_API }}
  GCF_AUTH_KEY: ${{ secrets.GCF_AUTH_KEY }}
  GH_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  SFPassword: ${{ secrets.SFPassword }}
  SFUserName: ${{ secrets.SFUserName }}

jobs:
  Recovery_compiling:
    if: "(! contains(toJSON(github.event.commits.*.message), '[skip-ci]'))"
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
#       - name: Cleaning Up Runner (Slimhub)
#        uses: rokibhasansagar/slimhub_actions@main

       - name: Preconfigure
         # /* if your branch name is other than the one which you dispatched workflow from then set it manually in the place of ${GITHUB_REF##*/}" */
         run: |
          sudo pacman --noconfirm -Syy
          sudo pacman --noconfirm -Scc
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R .
          echo "MANIFEST=https://github.com/SHRP/manifest.git -b v3_10.0" >> $GITHUB_ENV
 
       - name: Build
         uses: OneGameKoTT/Recovery-Compiler@arch-based

       - name: Upload Artifacts
         uses: actions/upload-artifact@v2.2.4
         with:
           name: dump files
           path: ~/builder/out/target/product/c18pro/*{.img,.zip}
