name: PBRP C18Pro
on:
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'Deploy Type (TEST/BETA/OFFICIAL)'
        required: true
        default: 'TEST'
      ChangeLogs:
        description: 'Build ChangeLogs'
        required: true
        default: 'Sync Latest Source'

env:
  BUILD_RELEASE_TYPE: ${{ github.event.inputs.DEPLOY_TYPE }}
  CHANGELOG: ${{ github.event.inputs.ChangeLogs }}
  BOT_API: ${{ secrets.BOT_API }}
  GCF_AUTH_KEY: ${{ secrets.GCF_AUTH_KEY }}
  GH_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  SFPassword: ${{ secrets.SFPassword }}
  SFUserName: ${{ secrets.SFUserName }}
  #TARGET: "define this if your target is not recoveryimage"
  #EXTRA_CMD: "Extra Commands Here"

jobs:
  Recovery_compiling:
    if: "(! contains(toJSON(github.event.commits.*.message), '[skip-ci]'))"
    runs-on: ubuntu-20.04

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main
         
       - name: Clean Up 002
         uses: easimon/maximize-build-space@master
         with:
           remove-dotnet: 'true'
           remove-haskell: 'true'
           root-reserve-mb: 512
           swap-size-mb: 1024
           build-mount-path: /home/runner
           
       - name: Cleaning Up Runner002
         uses: rokibhasansagar/slimhub_actions@main
         
       - name: Auto Adapt Manifest
         # /* if your branch name is other than the one which you dispatched workflow from then set it manually in the place of ${GITHUB_REF##*/}" */ 
         run: echo "MANIFEST=https://github.com/PitchBlackRecoveryProject/manifest_pb -b ${GITHUB_REF##*/}" >> $GITHUB_ENV

       - name: Export Vars
         run: |
              if [[ ${BUILD_RELEASE_TYPE} == "TEST" ]]; then echo "TEST_BUILD=true"  >> $GITHUB_ENV;fi
              if [[ ${BUILD_RELEASE_TYPE} == "BETA" ]]; then echo "BETA_BUILD=true"  >> $GITHUB_ENV;fi
              if [[ ${BUILD_RELEASE_TYPE} == "OFFICIAL" ]]; then echo "PB_OFFICIAL=true"  >> $GITHUB_ENV;fi

       - name: Recovery Compilation
         uses: OneGameKoTT/Recovery-Compiler@production
       
       - name: Upload recovery.img 
         uses: actions/upload-artifact@v2.2.4
         with:
           name: recovery.img
           path: ~/builder/out/target/product/c18pro/recovery.img
           
       - name: Upload PBRP.zip
         uses: actions/upload-artifact@v2.2.4
         with:
           name: Zip for twrp
           path: ~/builder/out/target/product/c18pro/PBRP-c18pro-.*\.zip
                  
