name: PBRP C18Pro
on:
  workflow_dispatch:
    inputs:
      VENDOR_REPO:
        description: 'Link to vendor repo'
        required: false
        default: 'https://github.com/deadYokai/proprietary_vendor_c18pro'

env:
  BOT_API: ${{ secrets.BOT_API }}
  GCF_AUTH_KEY: ${{ secrets.GCF_AUTH_KEY }}
  GH_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  SFPassword: ${{ secrets.SFPassword }}
  SFUserName: ${{ secrets.SFUserName }}
  VENDOR_REPO: ${{ inputs.VENDOR_REPO }}


jobs:
  Recovery_compiling:
    if: "(! contains(toJSON(github.event.commits.*.message), '[skip-ci]'))"
    runs-on: ubuntu-latest

    steps:
       - name: Cleaning Up Runner (Slimhub)
         uses: rokibhasansagar/slimhub_actions@main

       - name: Auto Adapt Manifest
         # /* if your branch name is other than the one which you dispatched workflow from then set it manually in the place of ${GITHUB_REF##*/}" */
         run: echo "MANIFEST=https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-10.0" >> $GITHUB_ENV

       - name: Compilation
         uses: deadYokai/Recovery-Compiler@production

       - name: Upload
         uses: actions/upload-artifact@v3.0.0
         with:
           name: dump files
           path: |
            /home/runner/builder/out/target/product/c18pro/*.zip
            /home/runner/builder/out/target/product/c18pro/*.img
